language: groovy

addons:
  chrome: stable
  firefox: latest

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

jobs:
  include:
    - stage: build
      script: mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: class-test
      script: mvn test -B
    - stage: system-test
      script: mvn verify -B -D geb.env=travis
