language: groovy

services:
  - docker

before_script:
  - docker network create grid
  - docker run -d -p 4444:4444 --net grid --name selenium-hub selenium/hub:latest
  - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm --name selenium-node-chrome selenium/node-chrome:latest
  - docker run -d --net grid -e HUB_HOST=selenium-hub -v /dev/shm:/dev/shm --name selenium-node-firefox selenium/node-firefox:latest

script:
  - mvn verify -B -D geb.env=travis

after_script:
  - cat target/geb-reports/**/*.html
  - docker stop selenium-node-firefox selenium-node-chrome selenium-hub
  - docker network rm grid
